create table if not exists public.devices (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  ring text not null,
  "deviceName" text not null default '',
  platform text not null default '',
  "osVersion" text not null default '',
  "serialNumber" text not null default '',
  "assetsReceived" text not null default ''
);

alter table public.devices enable row level security;

create policy "Allow anonymous read devices"
on public.devices
for select
to anon
using (true);

create policy "Allow anonymous insert devices"
on public.devices
for insert
to anon
with check (true);

create policy "Allow anonymous update devices"
on public.devices
for update
to anon
using (true)
with check (true);

create policy "Allow anonymous delete devices"
on public.devices
for delete
to anon
using (true);
